### ISSUE TITLE
Can't simply list names

### ISSUE THREAD

**Issue by PatrikTrefil** [lucc/khard#285]
AFAIK it is currently not possible to list just names. You can list emails, birthdays, phone numbers etc., but there is no option for names (first name + last name). If I am missing something, please let me know. 

Why is this needed? I am trying to write a script for dmenu to work with contacts. I need the user to select the contact name first, but I can not get the names. Generally, this would be useful in all kinds of scripts and programs.

Otherwise, I believe this is an important feature and should be implemented.

**Comment by d7415** [comment]
Hi. Try `khard list -F name`

**Comment by PatrikTrefil** [comment]
Yeah, that works. Thanks. 

I suggest You add more examples to Your docs. Also, I found it quite confusing, that the manpage does not include all the documentation available (one can get more information when passing the --help flag). I believe it would be convenient to have all the docs in one place.

**Comment by lucc** [comment]
@PatrikTrefil you are very welcome to open a PR with some examples for the docs!

I was to lazy to type all the argparse help text into the man page again,but there is a sphinx  argparse plugin which can do that. I did experiment with that a while back.  I will dig up the branch and let you  know.

**Comment by lucc** [comment]
@PatrikTrefil I found my branch and it uses https://github.com/alex-rudakov/sphinx-argparse to include the argparse stuff into the sphinx document, so that one does not have to type all the options and docs again. (There a quite a lot options in khard :)

I just played around with the branch again and noticed the following (i pushed the branch to github, so you can have a look: [feature/auto-man](https://github.com/scheibler/khard/tree/feature/auto-man)):
- the sphinx plugin generates a full listing which is quite long
- It seems one can add extra text between the parts that are auto generated which I think is good, but I have not tested this yet
- there is a bug upstream https://github.com/alex-rudakov/sphinx-argparse/issues/115 which was not fixed for a long time but which immediately would affect us
- it is unclear if and where the project is active: https://github.com/alex-rudakov/sphinx-argparse/issues/135 (although github says it's used by 1.7k other repositories  :cry: )

I am not really sure if I want to use that,, I will wait for an upstream decision first.  If you know of any other alternatives, I am happy to hear them.

**Comment by lucc** [comment]
Continued in #312
