### ISSUE TITLE
Matching on Phone Numbers

### ISSUE THREAD

**Issue by johannesk** [lucc/khard#301]
The Same phone number can be stored in many different formats:
- 017612345678
- 0176 12345678
- 0176-12345678
-  0176 123-45678
-  0176-123 456 78
- ...

Andoid tries to guess the area code and automatically inserts spaces into the number.

I am using khard with twinkle, similarly as described in https://github.com/scheibler/khard/pull/14 and khard stopped working as expected when updating to Ubuntu 22.04.

- Khard in version 0.15 did find any variant of this phone number when searching with `khard phone 017612345678`.
- Khard in version 0.17 only finds the contact when searching for the exact stored format
- Khard in version 0.17 does never find phone numbers with the `phone:` type, e.g.: `khard phone phone:0176`

**Comment by scheibler** [comment]
I've improved the phone number matching a few days ago. If you are still interested, please check out khards develop branch and tell me, what you think.

Please use the field query syntax like that:
`khard phone phone_numbers:017612345678`
For now the field is "phone_numbers" not "phone" but that might change before the next release.

You have to use the field query, so that khard strips everything from the contacts phone numbers and tries to match them with your input.

Disclaimer: The matching won't be perfect - too many vagaries, especially with the country code prefixes (+1 ect). But it should be improved a lot anyway.

**Comment by johannesk** [comment]
Thanks a lot. This does what I expected.
